export const CART_ACTION_TYPES = {
    SET_CART_PRODUCTS:'Cart/SET_CART_PRODUCTS',
    SET_CART_COUNT:'Cart/SET_CART_COUNT',
    SET_CART_TOTAL:'Cart/SET_CART_COUNT',
    TOGGLE_POPUP:'Cart/TOGGLE_POPUP'
}