const Data_books = [
    {
        id: 1,
        title: 'Science',
        routeName: 'science',
        items: [
            {
                id: 11,
                name: 'The Joy of Science',
                imageUrl: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1643835111l/60293448._SY475_.jpg',
                price: 25,
                category: 'Science',
                category_slug: 'science',
            },
            {
                id: 12,
                name: 'Insectpedia: A Brief Compendium of Insect Lore',
                imageUrl: 'https://pup-assets.imgix.net/onix/images/9780691210346.jpg',
                price: 18,
                category: 'Science',
                category_slug: 'science',
            },
            {
                id: 13,
                name: 'Geopedia: A Brief Compendium of Geologic Curiosities',
                imageUrl: 'https://m.media-amazon.com/images/I/41OWlRmSf7L.jpg',
                price: 35,
                category: 'Science',
                category_slug: 'science',
            },
            {
                id: 14,
                name: 'A Brief History of Time',
                imageUrl: 'https://media.s-bol.com/m2MrvpPKN68r/539x840.jpg',
                price: 25,
                category: 'Science',
                category_slug: 'science',
            },
            {
                id: 15,
                name: 'Cosmos (Sagan book)',
                imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/91Cnrbd3JwL.jpg',
                price: 18,
                category: 'Science',
                category_slug: 'science',
            },
            {
                id: 16,
                name: 'Pale Blue Dot: A Vision of the Human Future in Space',
                imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2S2P1mJpgfXSC8C1TsVdzUPBJDAlei9l1FD76t94keyU0VCpP',
                price: 14,
                category: 'Science',
                category_slug: 'science',
            },
            {
                id: 17,
                name: 'Thinking, Fast and Slow',
                imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/41wI53OEpCL._SX332_BO1,204,203,200_.jpg',
                price: 18,
                category: 'Science',
                category_slug: 'science',
            },
            {
                id: 18,
                name: 'A Short History of Nearly Everything',
                imageUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT3X9X_m2_lF5mcafa6Hih06h4zDZlk7_oDSLVXjkWgbbUbbtwL',
                price: 14,
                category: 'Science',
                category_slug: 'science',
            },
            {
                id: 19,
                name: 'Silent Spring',
                imageUrl: 'https://media.s-bol.com/Jl7YXK5yXNVJ/Xo30Z5o/550x823.jpg',
                price: 16,
                category: 'Science',
                category_slug: 'science',
            }
        ]
    },
    {
        id: 2,
        title: 'Romance',
        routeName: 'romance',
        items: [
            {
                id: 21,
                name: 'Pride and prejudice',
                imageUrl: 'http://prodimage.images-bn.com/pimages/9781499369748_p0_v3_s1200x630.jpg',
                price: 220,
                category: 'Romance',
                category_slug: 'romance',
            },
            {
                id: 22,
                name: 'Jane Eyre',
                imageUrl: 'https://kbimages1-a.akamaihd.net/fe3370f5-7e2c-4b70-aa06-09d5a63fc8ca/353/569/90/False/jane-eyre-445.jpg',
                price: 280,
                category: 'Romance',
                category_slug: 'romance',
            },
            {
                id: 23,
                name: 'The painted veil',
                imageUrl: 'https://m.media-amazon.com/images/I/41fepdDalJL.jpg',
                price: 110,
                category: 'Romance',
                category_slug: 'romance',
            },
            {
                id: 24,
                name: 'Anne of green gables',
                imageUrl: 'https://media.s-bol.com/g6PmMGDJ59YZ/lxOjk27/550x805.jpg',
                price: 160,
                category: 'Romance',
                category_slug: 'romance',
            },
            {
                id: 25,
                name: 'Sense and sensibility',
                imageUrl: 'https://images.penguinrandomhouse.com/cover/9780307386878',
                price: 160,
                category: 'Romance',
                category_slug: 'romance',
            },
            {
                id: 26,
                name: 'Little women',
                imageUrl: 'https://media.s-bol.com/vYl3GO8lVXBr/538x840.jpg',
                price: 160,
                category: 'Romance',
                category_slug: 'romance',
            },
            {
                id: 27,
                name: 'Air Jordan Limited',
                imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
                price: 190,
                category: 'Romance',
                category_slug: 'romance',
            },
            {
                id: 28,
                name: 'Timberlands',
                imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
                price: 200,
                category: 'Romance',
                category_slug: 'romance',
            }
        ]
    },
    {
        id: 3,
        title: 'History',
        routeName: 'history',
        items: [
            {
                id: 31,
                name: 'The Guns of August',
                imageUrl: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRaFykScx2obz8sFr-5lQMycKeolTAXUBaeyCSNvx7QACzAE1Am',
                price: 125,
                category: 'History',
                category_slug: 'history',
            },
            {
                id: 32,
                name: 'The Wager: A Tale of Shipwreck, Mutiny and Murder',
                imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsWZoUqXDflq-QmKRY8e_E_sm_29AUXBCNBpmHP8gei2POuxrF',
                price: 90,
                category: 'History',
                category_slug: 'history',
            },
            {
                id: 33,
                name: '1776',
                imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjmi6Bue5UCg-qGyU37iKsInnh9XEh8Q9crwvvUg1yh2cP4cYG',
                price: 90,
                category: 'History',
                category_slug: 'history',
            },
            {
                id: 34,
                name: 'The Rise and Fall of the Third Reich',
                imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuKjoKEqxvQtreY4fp-YpSr0CLaYWPUlkrqCcajaO_dl34Zqcd',
                price: 165,
                category: 'History',
                category_slug: 'history',
            },
            {
                id: 35,
                name: 'Nuclear War: A Scenario',
                imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv1OM_jML9ctgV4tP4gOV83ytXXSDNt6l80cMbolcghjSKSZBL',
                price: 185,
                category: 'History',
                category_slug: 'history',
            }
        ]
    },
    {
        id: 4,
        title: 'Justice',
        routeName: 'justice',
        items: [
            {
                id: 41,
                name: 'Just Mercy: A Story of Justice and Redemption',
                imageUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSLamdO3F5LsU0Mt-tPdSpzFodWfYWoW3AakCQqz0iIkx4uv3xK',
                price: 25,
                category: 'Justice',
                category_slug: 'Justice',
            },
            {
                id: 42,
                name: 'The Fire Next Time',
                imageUrl: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQVZybr63IL32-4T8J3QYMNKRaaRfR_6Zh0Ginz1w7USBA2g1BD',
                price: 20,
                category: 'Justice',
                category_slug: 'Justice',
            },
            {
                id: 43,
                name: 'Floral Dress',
                imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
                price: 80,
                category: 'Justice',
                category_slug: 'Justice',
            },
            {
                id: 44,
                name: 'Red Dots Dress',
                imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
                price: 80,
                category: 'Justice',
                category_slug: 'Justice',
            },
            {
                id: 45,
                name: 'Striped Sweater',
                imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
                price: 45,
                category: 'Justice',
                category_slug: 'Justice',
            },
            {
                id: 46,
                name: 'Yellow Track Suit',
                imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
                price: 135,
                category: 'Justice',
                category_slug: 'Justice',
            },
            {
                id: 47,
                name: 'White Blouse',
                imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
                price: 20,
                category: 'Justice',
                category_slug: 'Justice',
            }
        ]
    },
    {
        id: 5,
        title: 'Arts',
        routeName: 'arts',
        items: [
            {
                id: 51,
                name: 'Perspective Made Easy',
                imageUrl: 'https://m.media-amazon.com/images/I/415mnFNalwL.jpg',
                price: 325,
                category: 'Arts',
                category_slug: 'arts',
            },
            {
                id: 52,
                name: 'The Painter\'s Secret Geometry: A Study of Composition in Art',
                imageUrl: 'https://m.media-amazon.com/images/I/61Y1WQQ7pLL.jpg',
                price: 20,
                category: 'Arts',
                category_slug: 'arts',
            },
            {
                id: 53,
                name: 'Keys to Drawing',
                imageUrl: 'https://m.media-amazon.com/images/I/51mia9hy44L.jpg',
                price: 25,
                category: 'Arts',
                category_slug: 'arts',
            },
            {
                id: 54,
                name: 'Drawing for the Absolute Beginner: A Clear & Easy Guide to Successful Drawing',
                imageUrl: 'https://m.media-amazon.com/images/I/51wp49Qi9jL.jpg',
                price: 25,
                category: 'Arts',
                category_slug: 'arts',
            },
            {
                id: 55,
                name: 'Keys to Drawing with Imagination: Strategies and exercises for gaining confidence and enhancing your creativity',
                imageUrl: 'https://m.media-amazon.com/images/I/512lX4Uy11L.jpg',
                price: 40,
                category: 'Arts',
                category_slug: 'arts',
            },
            {
                id: 56,
                name: 'The Natural Way to Draw - A Working Plan for Art Study',
                imageUrl: 'https://m.media-amazon.com/images/I/51L8Y5MSUEL.jpg',
                price: 25,
                category: 'Arts',
                category_slug: 'arts',
            }
        ]
    }
]
export default Data_books;